package glimpse.api.gles

enum class BlendFactor(val complementary: BlendFactor) {
	ZERO(ONE),
	ONE(ZERO),
	SRC_COLOR(ONE_MINUS_SRC_COLOR),
	ONE_MINUS_SRC_COLOR(SRC_COLOR),
	DST_COLOR(ONE_MINUS_DST_COLOR),
	ONE_MINUS_DST_COLOR(DST_COLOR),
	SRC_ALPHA(ONE_MINUS_SRC_ALPHA),
	ONE_MINUS_SRC_ALPHA(SRC_ALPHA),
	DST_ALPHA(ONE_MINUS_DST_ALPHA),
	ONE_MINUS_DST_ALPHA(DST_ALPHA),
	CONSTANT_COLOR(ONE_MINUS_CONSTANT_COLOR),
	ONE_MINUS_CONSTANT_COLOR(CONSTANT_COLOR),
	CONSTANT_ALPHA(ONE_MINUS_CONSTANT_ALPHA),
	ONE_MINUS_CONSTANT_ALPHA(CONSTANT_ALPHA);

	val complementaryPair: Pair<BlendFactor, BlendFactor> by lazy { this to complementary }
}
